language: node_js

node_js: lts/*

if: tag IS blank

install:
  - |
    npm ci
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

stages:
  - benchmark

jobs:
  include:
    - stage: benchmark
      script:
        - npm run benchmark
        - npm test
